services:
    node:
        build: .
        image: chrysalis/gethimage:1.2
        expose:
            - "30303"
        volumes:
            - connection_data:/tmp

 
 volumes:
    connection_data:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: "size=10m"
            
 ethstats:
   container_name: ethstat
   image: chrysalis/ethstat
  ports:
    - "30303:30303"
    - "8545:8545"
command: geth --rpc --rpcaddr "0.0.0.0" -rpcapi "eth,miner,personal"
